### ISSUE TITLE
✨ Feature: 취향저격 소확행 화면 > 취향저격 소확행 기획 개선

### ISSUE THREAD

**Issue by taewoojeong** [9uttery/MADII-iOS#69]
### Descrpiton
최향저격 소확행 기획이 바뀜에 따라 변경된 api 호출과 UI변경에 대한 추가적인 개발이 필요합니다!

### Todo
- [x] 취향저격 소확행 List Data 비어있을 때 애니메이션 추가
- [x] 취향저격 소확행 추천 뷰에서 다시고르기 버튼 추가
- [x] 취향저격 소확행 키워드 버튼 코드 최적화
- [x] 오늘의 플레이리스트 추가 버튼 문구 변경
- [x] 취향저격 소확행 List eclipse에서 북마크로 변경
- [x] 취향저격 소확행 북마크 api 연동
- [x] 오늘의 플레이리스트 추가 뷰 디자인 변경
- [x] 오늘의 플레이리스트 추가 뷰 Dynamic Gradient Border Animations 추가

### Information / ETC
- 긴급도: `High` (High/Mid/Low로 적어주세요!)
- 예상 소요 시간: `2d+` (시간은 h, 하루 이상 걸린다면 d!)
