### ISSUE TITLE
🐛 Bug: 취향저격 소확행 HomeView에서 나가는 방식 변경

### ISSUE THREAD

**Issue by taewoojeong** [9uttery/MADII-iOS#75]
### Descrpiton
(작업의 상세 설명을 적어주세요!)

### Todo
- [x] RecommendView에서 RecommendJoyView로 navigation하지 않고 오른쪽에 있게 두기
- [x] 오늘의 플레이리스트 추가하기 누르면 RecommendJoyView 보이게 offset 수정
- [x] 오늘의 플레이리스트 추가하고 dismiss 하기
- [x] naivgationTitle 나오게 하기
- [ ] RecommendJoyView Animation도 넣어주기

### Information / ETC
- 긴급도: `High` (High/Mid/Low로 적어주세요!)
- 예상 소요 시간: `1h+` (시간은 h, 하루 이상 걸린다면 d!)
