### ISSUE TITLE
✨ Feature: 취향저격 소확행 UI 개선 반영 & 문구 수정과 같은 QA

### ISSUE THREAD

**Issue by taewoojeong** [9uttery/MADII-iOS#82]
### Descrpiton
(작업의 상세 설명을 적어주세요!)

### Todo

- [x] 취향저격 소확행 UI 디테일 개선(QA-152)
- [x] 취향저격 소확행 애니메이션 UI 디테일 개선(QA-153)
- [x] 취향저격 소확행 앨범 북마크 오플리 추가하기 버튼 삭제(QA-155)
- [x] 취향저격 소확행 배너 버튼 디자인 변경(QA-156)
- [x] 개별 소확행 ··· 버튼 눌렀을 때 나오는 바텀시트 내 문구 수정 (&를 · 로 일괄 수정)
- [x] 기록했을 때 뜨는 토스트 메시지 온점 삭제 (피그마 화면 R_1_3)

### Information / ETC
- 긴급도: `High` (High/Mid/Low로 적어주세요!)
- 예상 소요 시간: `1h+` (시간은 h, 하루 이상 걸린다면 d!)
